### ISSUE TITLE
Investigate -  text field Out-Of-Stock Error

### ISSUE THREAD

**Issue by potteryhouse** [potteryhouse/stock_by_attribute_1.5.3#12]
Investigate user comment:

"So here's the story:
I have one text field that is for customers to add their personalisation which is not required for stock purposes - I then have two drop downs - one for design colour and one for mug type, both are required for stock purposes.

If I add all the above details to an order the checkout shows "out of stock". If I leave the personalisation field blank its fine.

If I add the personalisation field into SBA as a variant and assign it a qty its also fine however if I did this I would then have to spend ages cleaning up the Amazon product feed.

Is this the only way of dealing with the Gift wrap issue?"

http://www.zen-cart.com/showthread.php?47180-Stock-by-Attribute-v4-0-addon-for-v1-3-5-1-3-9&p=1250163#post1250163

=====================
Initial Review and Reply:

I see what you are saying, I will have a look at this and get back to you. 
I think it should be a small change to one of the tests in the attributes.php file, it should be ignoring text fields.
I had thought I had accounted for this already...

**Comment by mc12345678** [comment]
Need to figure out how to "clean this up" and get the relevant data; however, in relation to the original question/issue with text attributes.  At least if a variant is built such that all attributes are associated with a single variant (can't recall testing with them all individual), with dynamic dropdowns active for multiple products (I believe works also without DD), then first of all until the sequenced dropdown is built better, all attribute "styles" appear as originally "designated", and the text field is/should be treated like any other attribute and can be empty or have content (attributes controller settings may affect this) and the product will be treated like any other product with attributes.  The same is now true for file uploads and the use of the plugin Product Attributes Grid for which SBA has been uniquely modified to work.

This issue is not yet closed (cleanup/movement of issues needed), but the original topic is addressed.  Code can be found at: https://github.com/mc12345678/Stock_By_Attributes_Combined

**Comment by mc12345678** [comment]
I believe that all aspects of this issue have been addressed (in the latest version of this at https://github.com/mc12345678/Stock_By_Attributes_Combined).  If incorrect please [begin a new issue](https://github.com/mc12345678/Stock_By_Attributes_Combined/issues) at that location using the clickable link to the left.

From "brief" review, the following issues appear to have been identified:
- At the root of this discussion was the text field and how it plays into the overall category of stock.  Text fields have been added to SBA to work as a variant or as an attribute associated with a variant "group".  I have an [open issue](https://github.com/mc12345678/Stock_By_Attributes_Combined/issues/26) related to how the system responds if the text attribute is considered required, but generally speaking the text attribute is now supported (Dynamic Dropdowns not yet, but it will get there and even if not multiple attributes do still work.)
- Deletion of a variant that contains an option value that has been deleted from the attributes controller.
- Deletion of an option name/or option value from the attributes controller will prevent display of those items when generating a new product variant. 
- Continued display of a selectable variant option when that specific variant has gone out-of-stock (this works in both Dynamic Dropdowns and the potteryhouse simple SBA dropdown list).

Closing this topic, if I have missed something, please [initiate a new issue](https://github.com/mc12345678/Stock_By_Attributes_Combined/issues).
